(load "~/.emacs.d/config/general")
(load "~/.emacs.d/config/packages")
(load "~/.emacs.d/config/php")
(load "~/.emacs.d/config/session")
(load "~/.emacs.d/config/shortcuts")
(load "~/.emacs.d/config/display")
(load "~/.emacs.d/config/scheme")
(load "~/.emacs.d/config/rss")
